trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    npm install
    npm run cypress --spec="cypress/e2e/1-getting-started/login_searchproduct.spec.js"
  displayName: 'Run Cypress tests'